name: Release

on:
  release:
    types: ['published']

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-binaries:
    name: Build Standalone Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Set default version string
        run: |
          sed -i -e 's/dev-build/${{ github.event.release.tag_name }}/g' src/config.ts

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.7.x

      - name: Build Dashboard
        run: deno task dashboard:build

      - name: Compile Binary
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            SUFFIX=".exe"
          else
            SUFFIX=""
          fi
          deno task compile:server --target ${{ matrix.target }} --output server-${{ matrix.target }}$SUFFIX src/server.ts
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            SUFFIX=".exe"
          else
            SUFFIX=""
          fi
          gh release upload ${{ github.event.release.tag_name }} server-${{ matrix.target }}$SUFFIX

  release:
    name: Release New Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Set default version string
        run: |
          sed -i -e 's/dev-build/${{ github.event.release.tag_name }}/g' src/config.ts

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}