name: Release

on:
  release:
    types: ['published']

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: vx.x.x

      - name: Prepare release
        run: |
          sed -i -e 's/dev-build/${{ github.event.release.tag_name }}/g' config.ts
          mkdir build
          deno task build-docker-target
          mkdir stg
          cp -r build/server stg/server
          cp -r static stg/static
          cp -r templates stg/templates
          mkdir release
          tar -czvf release/x86_64-unknown-linux-gnu.tar.gz ./stg/*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          allowUpdates: true
          omitBodyDuringUpdate: true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}